import React, { useEffect, useState } from "react";

import Head from "next/head";
import { Container, Tab, Nav } from "react-bootstrap";

import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";
import MapMain from "@/components/Map";
import SocialMedia from "@/components/Common/SocialMedia";
import Simulation from "@/components/Simulation";
import Combatants from "@/components/Combatants";

const projectTabs = [
  {
    title: "Compatatnt Selecttion",
  },
  {
    title: "Map Selection",
  },
  {
    title: "Simulation",
  },
];

export default function Home() {
  const [activeTab, setActiveTab] = useState(projectTabs[0].title);

  const handleTabChange = (selectedTab) => {
    setActiveTab(selectedTab);
  };

  const handleNext = () => {
    // Logic to determine the next tab based on the current active tab
    // Example: Find the index of the current active tab and move to the next one
    const currentIndex = projectTabs.findIndex(
      (tab) => tab.title === activeTab
    );
    const nextIndex = (currentIndex + 1) % projectTabs.length;
    const nextTab = projectTabs[nextIndex].title;

    setActiveTab(nextTab);
  };

  const handleBack = () => {
    // Logic to determine the previous tab based on the current active tab
    // Example: Find the index of the current active tab and move to the previous one
    const currentIndex = projectTabs.findIndex(
      (tab) => tab.title === activeTab
    );
    const previousIndex =
      (currentIndex - 1 + projectTabs.length) % projectTabs.length;
    const previousTab = projectTabs[previousIndex].title;

    setActiveTab(previousTab);
  };

  return (
    <>
      <Head>
        <title>Encountera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="d-none d-lg-block">
          <SocialMedia />
        </div>
        <div className="ts-main-content">
          <Container fluid className="ts-container">
            <Tab.Container
              id="GiveAwayTabs"
              defaultActiveKey={projectTabs[0].title}
              activeKey={activeTab}
              onSelect={handleTabChange}
            >
              <div className="d-flex justify-content-center mb-08">
                <Nav variant="pills" className="ts-tabs ts-tabs-primary">
                  {projectTabs.map((tabItem, index) => {
                    return (
                      <Nav.Item className="text-center " key={index}>
                        <Nav.Link eventKey={tabItem.title}>
                          {" "}
                          <span> {tabItem.title} </span>
                        </Nav.Link>
                      </Nav.Item>
                    );
                  })}
                </Nav>
              </div>

              <Tab.Content>
                <Tab.Pane eventKey={projectTabs[0].title}>
                  <Combatants />
                </Tab.Pane>
                <Tab.Pane eventKey={projectTabs[1].title}>
                  <MapMain />
                </Tab.Pane>
                <Tab.Pane eventKey={projectTabs[2].title}>
                  <Simulation />
                </Tab.Pane>
              </Tab.Content>
            </Tab.Container>

            <div className="d-flex justify-content-center gap-4 mt-5">
              <button
                className="btn ts-btn ts-btn--lg fw-bold ts-btn-outline-secondary"
                onClick={handleBack}
              >
                BACK
              </button>
              <button
                className="btn ts-btn ts-btn--lg fw-bold ts-btn-primary"
                onClick={handleNext}
              >
                Next
              </button>
            </div>
          </Container>
        </div>
        <Footer />
      </main>
    </>
  );
}
