import Head from "next/head";
import { Container, Tab, Nav } from "react-bootstrap";

import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import MapMain from "@/components/Map";
import SocialMedia from "@/components/Common/SocialMedia";
import Simulation from "@/components/Simulation";

const projectTabs = [
  {
    title: "Compatatnt Selecttion",
  },
  {
    title: "Map Selection",
  },
  {
    title: "Simulation",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Encountera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="d-none d-lg-block">
          <SocialMedia />
        </div>
        <div className="ts-main-content">
          <Container fluid className="ts-container">
            <Tab.Container
              id="GiveAwayTabs"
              defaultActiveKey={projectTabs[2].title}
            >
              <div className="d-flex justify-content-center mb-08">
                <Nav variant="pills" className="ts-tabs ts-tabs-primary">
                  {projectTabs.map((tabItem, index) => {
                    return (
                      <Nav.Item className="text-center " key={index}>
                        <Nav.Link eventKey={tabItem.title}>
                          {" "}
                          <span> {tabItem.title} </span>
                        </Nav.Link>
                      </Nav.Item>
                    );
                  })}
                </Nav>
              </div>

              <Tab.Content>
                <Tab.Pane eventKey={projectTabs[0].title}>
                  {projectTabs[0].title}
                </Tab.Pane>
                <Tab.Pane eventKey={projectTabs[1].title}>
                  <MapMain />
                </Tab.Pane>
                <Tab.Pane eventKey={projectTabs[2].title}>
                  <Simulation />
                </Tab.Pane>
              </Tab.Content>
            </Tab.Container>
          </Container>
        </div>
        <Footer />
      </main>
    </>
  );
}
