import { useEffect, useState } from "react";
import { Accordion, Spinner } from "react-bootstrap";

import Head from "next/head";

import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";
import SocialMedia from "@/components/Common/SocialMedia";
import { ArrowLeft } from "@/Icons/index";

import { toast } from "react-toastify";

import { useDispatch } from "react-redux";

import axiosInstance from "@/axios";

export default function Home() {
  const [simulationHistory, setSimulationHistory] = useState(null);
  const dispatch = useDispatch();
  const getSimulationsHistory = async () => {
    try {
      dispatch({ type: "SIMULATION_HISTORY_START" });
      const accessToken = localStorage.getItem("AccessToken");
      const response = await axiosInstance.get("get-simulation-history", {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });
      console.log(response.data);
      setSimulationHistory(response.data);
      // Show success toast
      toast.success("Simulatiuon History Get successfully", {
        position: "bottom-right",
        autoClose: 3000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });
      dispatch({ type: "SIMULATION_HISTORY_SUCCESS" });
    } catch (error) {
      console.error("Password reset error:", error);

      // Show error toast
      toast.error("An error occurred during password reset", {
        position: "bottom-right",
        autoClose: 3000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      });

      // Propagate the error for the component to handle
      throw error;
    }
  };

  useEffect(() => {
    getSimulationsHistory();
  }, []);
  return (
    <>
      <Head>
        <title>Encountera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="ts-main-wrapper">
          <div className="d-none d-lg-block">
            <SocialMedia />
          </div>
          <div className="my-5">
            <div className="ts-container">
              <a
                className="ts-btn ts-btn-gray rounded-3  px-3 d-inline-flex  align-items-center mb-04"
                href="./"
              >
                {" "}
                <span className="me-2">
                  <ArrowLeft Width="16" Height="16" Fill="white" />
                </span>
                Back
              </a>

              <h1 className="ts-fs-40 text-uppercase text-center mb-09 fw-bold">
                simulation results
              </h1>
              <div className="ts-card-2 px-4 py-5">
                {simulationHistory ? (
                  <Results simulationHistory={simulationHistory} />
                ) : (
                  <div className="d-flex justify-content-center">
                    <Spinner animation="border" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </Spinner>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}

function Results({ simulationHistory }) {
  return (
    <Accordion defaultActiveKey="0">
      {simulationHistory.map((simulation, index) => (
        <AccordionItem key={index} index={index} simulation={simulation} />
      ))}
    </Accordion>
  );
}

function AccordionItem({ simulation, index }) {
  let encounteredDoubleBraces = 0;

  const formattedStats = simulation.stats.replace(
    /(\{(?!\s*\n))|(\})|,|(\}\})/g,
    (match, openingBrace, closingBrace, doubleBraces) => {
      if (openingBrace) {
        return `${openingBrace}<br/>`;
      } else if (closingBrace && encounteredDoubleBraces === 0) {
        encounteredDoubleBraces++;
        return `${closingBrace}<br/>`;
      } else if (closingBrace && encounteredDoubleBraces === 1) {
        encounteredDoubleBraces = 0;
        return `${closingBrace}<br/>`;
      } else if (doubleBraces) {
        return `${closingBrace}<br/>${closingBrace}`;
      } else if (match === ",") {
        return "<br/>";
      } else {
        return "<br/>";
      }
    }
  );

  console.log(formattedStats);

  return (
    <Accordion.Item eventKey={index}>
      <Accordion.Header>
        <div className="row row-cols-2 row-cols-md-4 w-100 ts-text-gray-2">
          <div className="text-center mb-4 mb-md-0">
            <h3 className="ts-fs-22 text-uppercase fw-bold">DATE</h3>
            <p className="ts-fs-20 fw-medium mb-0">
              {simulation.simulation_date}
            </p>
          </div>
          <div className="text-center mb-4 mb-md-0">
            <h3 className="ts-fs-22 text-uppercase fw-bold">iterntions</h3>
            <p className="ts-fs-20 fw-medium mb-0">{simulation.iterations}</p>
          </div>
          <div className="text-center ">
            <h3 className="ts-fs-22 ts-text-skyblue text-uppercase fw-bold">
              Blue Team
            </h3>
            <ul className="list-unstyled p-0 ts-fs-20 fw-medium mb-0">
              {simulation.blue.map((name, index) => {
                return <li key={index}>{name}</li>;
              })}
            </ul>
          </div>
          <div className="text-center">
            <h3 className="ts-fs-22 ts-text-red text-uppercase fw-bold">
              Red Team
            </h3>
            <ul className="list-unstyled p-0 ts-fs-20 fw-medium mb-0">
              {simulation.red.map((name, index) => {
                return <li key={index}>{name}</li>;
              })}
            </ul>
          </div>
        </div>
      </Accordion.Header>
      <Accordion.Body>
        {/* <pre>
          <code>{simulation.stats}</code>
        </pre> */}
        <div className="d-flex justify-content-center">
          <div dangerouslySetInnerHTML={{ __html: formattedStats }} />
        </div>
        {/* <br />
        <div dangerouslySetInnerHTML={{ __html: simulation.stats }} /> */}
        {/* <div>
          <JSONView src={jsonData} />
        </div> */}
        {/* <JsonView
          data={simulation.stats}
          shouldExpandNode={allExpanded}
          // style={defaultStyles}
        /> */}
        {
          // <pre>
          //   <code>{JSON.stringify(simulation.stats, null, 2)}</code>
          // </pre>
        }
      </Accordion.Body>
    </Accordion.Item>
  );
}
